{
 "title": "All in One Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "clustername",
    "label": "DC/OS Cluster",
    "query": "label_values(dcos_cluster_name)"
   }
  ]
 },
 "panels": [
  { "title": "DC/OS", "type": "row", "gridPos": { "h": 1, "w": 16, "x": 0, "y": 0 } },
  {
   "title": "Mesos CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(mesos_slave_cpus_percent{dcos_cluster_name=\"$clustername\"})",
     "legendFormat": "分配"
    },
    {
     "expr": "avg(max by(instance)(cpu_usage_system{dcos_cluster_name=\"$clustername\"} + cpu_usage_user{dcos_cluster_name=\"$clustername\"} + cpu_usage_guest{dcos_cluster_name=\"$clustername\"}) / 100)",
     "legendFormat": "使用"
    }
   ]
  },
  {
   "title": "Mesos 内存",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(sum by (host) (mem_used{dcos_cluster_name=\"$clustername\"}))",
     "legendFormat": "分配"
    },
    {
     "expr": "sum(sum by (host) (mem_rss_bytes{dcos_cluster_name=\"$clustername\"}))",
     "legendFormat": "使用"
    }
   ]
  },
  {
   "title": "Kafka每秒消息数",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_MessagesInPerSec_5MinuteRate{service_name=\"kafka\"})"
    }
   ]
  },
  {
   "title": "Kafka Topic数",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (topic) (kafka_server_BrokerTopicMetrics_MessagesInPerSec_5MinuteRate{executor_name=\"kafka\",service_name=\"kafka\"}))"
    }
   ]
  },
  {
   "title": "Cassandra运行节点",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_frameworks_tasks_active{framework_name=\"cassandra\", task_state=\"task_running\"}"
    }
   ]
  },
  {
   "title": "Cassandra连接客户端",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_Client_connectedNativeClients{service_name=\"cassandra\"})",
     "legendFormat": "Clients Count"
    }
   ]
  },
  {
   "title": "Mesos 磁盘",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_slave_disk_percent{dcos_cluster_name=\"$clustername\"})",
     "legendFormat": "分配"
    }
   ]
  },
  {
   "title": "Mesos GPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_master_gpus_percent{dcos_cluster_name=\"$clustername\"})",
     "legendFormat": "分配"
    }
   ]
  },
  {
   "title": "Mesos 运行负载",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_master_frameworks_connected{dcos_cluster_name=\"$clustername\"})",
     "legendFormat": "Frameworks"
    },
    {
     "expr": "count(count by(container_id) (cpus_limit{dcos_cluster_name=\"$clustername\"}))",
     "legendFormat": "Tasks"
    }
   ]
  },
  {
   "title": "Mesos Master",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(system_uptime{job=\"master-metrics\"})",
     "legendFormat": "Masters"
    }
   ]
  },
  {
   "title": "Mesos Agent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(system_uptime{job=\"agent-metrics\"})",
     "legendFormat": "Agent"
    }
   ]
  },
  { "title": "腾讯云", "type": "row", "gridPos": { "h": 1, "w": 16, "x": 0, "y": 24 } },
  {
   "title": "MySQL慢查询",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "expr": "qce_cdb_slowqueries_sum", "legendFormat": "{{instance_name}}" }
   ]
  },
  {
   "title": "Mongo QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "targets": [
    { "expr": "qce_cmongo_qps_max", "legendFormat": "{{instance_name}}" }
   ]
  },
  {
   "title": "Redis内存使用率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "qce_redis_storageusmin_avg", "legendFormat": "{{instance_name}}" }
   ]
  },
  {
   "title": "ES健康节点",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_nodes",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Elasticsearch 总分片数",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 37 },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Elasticsearch 未分配分片数",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_unassigned_shards",
     "legendFormat": "{{cluster}}"
    }
   ]
  }
 ]
}